global:
  scrape_interval: 15s 
scrape_configs: 
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['localhost: 9090']

  - job_name: 'nodes'
    static_configs: 
      - targets: ['192.168.1.1:9100'] 
      - targets: ['192.168.4.1:9100'] 
      - targets: ['192.168.4.2:9100']